In [1]:
import pandas as pd
script = pd.read_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\IS\Python for DS- Project\conv.txt", header = None,delimiter = ':')
script.columns = ['Name', 'Speech']
script.to_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\IS\Python for DS- Project\conv2.txt", index = None)
script

             Name                                             Speech
0            WILL   I’ve never seen wildlings do a thing like thi...
1    WAYMAR ROYCE                             How close did you get?
2            WILL                            Close as any man would.
3           GARED                   We should head back to the wall.
4           ROYCE                          Do the dead frighten you?
..            ...                                                ...
106           NED                           Tell me about Jon Arryn.
107        ROBERT   One minute he was fine, and then … Burned rig...
108           NED                                       We both did.
109        ROBERT   He never had to teach you much, but me … You ...
110           NED                                               Aye.

[111 rows x 2 columns]

In [3]:
import numpy as np
name_1 = script["Name"].unique()
name_1

array(['WILL', 'WAYMAR ROYCE', 'GARED', 'ROYCE', 'JON', 'SEPTA MORDANE',
       'SANSA', 'NED', 'ROBB', 'CASSEL', 'CATELYN', 'BRAN', 'THEON',
       'CERSEI', 'JAIME', 'ROBERT', 'ARYA'], dtype=object)

In [4]:
df = script.sort_values("Name")
df['Speech'] = df.groupby(['Name'])['Speech'].transform(lambda x : ' '.join(x))
df = df.drop_duplicates()

In [5]:
def to_split(txt):
    return txt.split()
df['Speech'] = df['Speech'].apply(lambda x : list(set(to_split(x))))
df = df.reset_index(drop=True)
df

             Name                                             Speech
0            ARYA  [the, Imp?, Jaime, queen’s, brother., That’s, ...
1            BRAN  [saw, is, a, true, mother’s, was, now!, White,...
2          CASSEL  [is, law,, a, hills., Stark., law, rode, the, ...
3         CATELYN  [many, outsider, Ned., is, grow, an, so, climb...
4          CERSEI  [beast., is, a, should, can, find, the, Surely...
5           GARED  [track, See, won’t, went., should, wall., were...
6           JAIME  [didn’t, while, or, is, who, a, can, died, an,...
7             JON  [your, is, a, Stark?, were, Stark., it?, not, ...
8             NED  [who, sees., was, not, you,, Tough, yours., An...
9            ROBB  [your, hear, hair., is, a, better, prince, tha...
10         ROBERT  [Ooh., skulls, was, haven’t, but, fat., teach,...
11          ROYCE  [your, is, won’t, a, away., camp., run, on, Yo...
12          SANSA  [Thank, you, up?, you., please, Will, up., Wou...
13  SEPTA MORDANE  [Well, done., always., I, love, the, to, in, t...
14          THEON  [your, girls, all, a, southern, not, he, take,...
15   WAYMAR ROYCE                       [you, get?, close, How, did]
16           WILL  [even, a, ever, were, did, not, never, the, co...

In [6]:
df.to_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\IS\Python for DS- Project\speakerz.txt", header= None, index= None)
with open(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\IS\Python for DS- Project\speakerz.txt", 'r') as file:
    i = 1
    for row in file:
        with open("Character"+str(i)+".txt", 'w') as c:
             c.write(row.replace(",", "\n"))
        i+=1